apiVersion: apps/v1
kind: Deployment
metadata:
  name: tt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tt
  template:
    metadata:
      name: tt
      labels:
        app: tt
    spec:
      containers:
      - image: micgn/timetracker:v1.0
        name: tt
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 4848
          protocol: TCP
#        livenessProbe:
#          httpGet:
#            path: /tt/status
#            port: 8080
#        readinessProbe:
#          httpGet:
#            path: /tt/status
#            port: 8080
